In [1]:
import numpy as np

In [20]:
A = np.arange(10)
A


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# starting from 0 to 10 and making 10 elements
B = np.random.randint(0,10,(1,10))
B

array([[4, 0, 6, 7, 1, 9, 2, 9, 3, 1]])

In [22]:
A.shape

(10,)

In [23]:
B.shape

(1, 10)

In [25]:
# adding new axis to array
C = A[np.newaxis,:]
C.shape

(1, 10)

In [26]:
B.shape

(1, 10)

In [27]:
D = B+C
D

array([[ 4,  1,  8, 10,  5, 14,  8, 16, 11, 10]])

In [28]:
# o 
# 2
# 4
# ⬇️
# shape
# ⬇️
# 1 2 3
# ⬇️
# np.squeeze().shape
# ⬇️
# 3
D = np.squeeze(D)
D.shape

(10,)

In [29]:
# D and A, both have same number of components. 
D

array([ 4,  1,  8, 10,  5, 14,  8, 16, 11, 10])

In [30]:
A 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# for adding multiple arrays together:
C = np.add(A,D)
C

array([ 4,  2, 10, 13,  9, 19, 14, 23, 19, 19])

In [33]:
# sum is using for single array and multiple elements of the that array:
C = np.sum(A)
C

45

In [49]:
A = np.arange(80).reshape(2,2,5,4)
A
#A.ndim

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]],


       [[[40, 41, 42, 43],
         [44, 45, 46, 47],
         [48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]],

        [[60, 61, 62, 63],
         [64, 65, 66, 67],
         [68, 69, 70, 71],
         [72, 73, 74, 75],
         [76, 77, 78, 79]]]])

In [44]:
# axis 0 is first dimension(2,2,5,4), 1 is second and ect.
# sum the two first with the two second.(1 by 3 and 2 by 4)
B = A.sum(axis=0)
B

array([[[ 40,  42,  44,  46],
        [ 48,  50,  52,  54],
        [ 56,  58,  60,  62],
        [ 64,  66,  68,  70],
        [ 72,  74,  76,  78]],

       [[ 80,  82,  84,  86],
        [ 88,  90,  92,  94],
        [ 96,  98, 100, 102],
        [104, 106, 108, 110],
        [112, 114, 116, 118]]])

In [45]:
B.shape

(2, 5, 4)

In [47]:
# sum 1 by 2 and 3 by 4:
B = A.sum(axis=1)
B

array([[[ 20,  22,  24,  26],
        [ 28,  30,  32,  34],
        [ 36,  38,  40,  42],
        [ 44,  46,  48,  50],
        [ 52,  54,  56,  58]],

       [[100, 102, 104, 106],
        [108, 110, 112, 114],
        [116, 118, 120, 122],
        [124, 126, 128, 130],
        [132, 134, 136, 138]]])

In [51]:
# sum all elements in each column:
B = A.sum(axis=2)
B

array([[[ 40,  45,  50,  55],
        [140, 145, 150, 155]],

       [[240, 245, 250, 255],
        [340, 345, 350, 355]]])

In [52]:
# sum all elements in each array:
B = A.sum(axis=3)
B

array([[[  6,  22,  38,  54,  70],
        [ 86, 102, 118, 134, 150]],

       [[166, 182, 198, 214, 230],
        [246, 262, 278, 294, 310]]])

In [54]:
B.shape

(2, 2, 5)

In [56]:
C = np.sum(B,axis=2)
C

array([[ 190,  590],
       [ 990, 1390]])

In [57]:
C.shape

(2, 2)

In [58]:
C.sum(axis=0)

array([1180, 1980])

In [59]:
C.sum(axis=1)

array([ 780, 2380])

In [60]:
n = 1000000
A = np.random.rand(n)
B = np.random.rand(n)
%timeit A+B
%timeit np.add(A,B)

526 µs ± 15.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
550 µs ± 26.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [62]:
#subtract
A = np.random.rand(10)
B = np.random.rand(10)
C = np.subtract(A,B)
C

array([ 0.46620457, -0.2653115 , -0.37655981, -0.19055266,  0.50797965,
       -0.75434126, -0.3853975 ,  0.84543473,  0.65416602, -0.11021379])

In [64]:
C = A-B
C

array([ 0.46620457, -0.2653115 , -0.37655981, -0.19055266,  0.50797965,
       -0.75434126, -0.3853975 ,  0.84543473,  0.65416602, -0.11021379])

In [65]:
#multiply
C = np.multiply(A,B)
D = A*B

In [66]:
#power
C = np.power(A,B)
C = A**B

In [67]:
C

array([0.92243819, 0.43817797, 0.61112885, 0.6520373 , 0.93273157,
       0.23131652, 0.57561398, 0.99616009, 0.97276363, 0.60917711])

In [69]:
A%B

array([0.17336865, 0.11276727, 0.60572553, 0.56982843, 0.02468556,
       0.22390845, 0.55624413, 0.01696389, 0.18428049, 0.28834881])

In [70]:
A = np.random.randint(1,10,10)
A.shape

(10,)

In [71]:
B = np.random.randint(1,10,10)
A%B

array([2, 0, 4, 2, 2, 0, 0, 0, 2, 2])

In [72]:
C = np.mod(A,B)
C

array([2, 0, 4, 2, 2, 0, 0, 0, 2, 2])

In [75]:
A = np.arange(100).reshape(5,20)
A = A.mean(axis=0)

In [76]:
A.shape

(20,)

In [77]:
A = np.random.rand(1000).reshape(5,4,2,5,5)

In [78]:
A.shape

(5, 4, 2, 5, 5)

In [80]:
B = A.sum(axis=3)
B.shape 

(5, 4, 2, 5)

In [81]:
B = A.sum(axis=2)
B.shape 

(5, 4, 5, 5)

In [82]:
B = A.sum(axis=4)
B.shape 

(5, 4, 2, 5)

In [83]:
B.sum()

515.9075785069535

In [84]:
B.sum(axis=0).sum(axis=0).sum(axis=0).sum()

515.9075785069535

In [85]:
# Trigonometric functions
A = np.random.rand(5)
np.sin(A)

array([0.41070063, 0.34183224, 0.80563484, 0.46382075, 0.79707432])

In [86]:
np.cos(A)

array([0.91177025, 0.93976099, 0.59241245, 0.88592907, 0.60388122])

In [87]:
np.arcsin(A)

array([0.43699896, 0.3563607 , 1.21321552, 0.50328186, 1.17433905])

In [88]:
np.arccos(A)

array([1.13379737, 1.21443563, 0.35758081, 1.06751446, 0.39645728])

In [89]:
A = np.random.rand(5)
B = np.random.rand(5)
R = np.greater(A,B)
R

array([False,  True,  True, False, False])

In [91]:
R = A>B
R

array([False,  True,  True, False, False])

In [92]:
A = np.random.rand(10)
R1 = A<0.5
R2 = ~R1

In [93]:
R1

array([ True, False,  True, False, False, False,  True,  True, False,
       False])

In [94]:
R2

array([False,  True, False,  True,  True,  True, False, False,  True,
        True])

In [95]:
R2 = np.logical_not(R1)
R2

array([False,  True, False,  True,  True,  True, False, False,  True,
        True])

In [114]:
A = np.random.rand(20)
idx = (A>0.2) & (A<.08)
idx

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [116]:
#missing values
A = np.random.rand(5)
A[3] = np.nan
A

array([0.91986374, 0.85813103, 0.98522778,        nan, 0.59155627])

In [117]:
A.sum()

nan

In [119]:
#egnoring the nan values
np.nansum(A)

3.354778816033858

In [120]:
np.isnan(A)

array([False, False, False,  True, False])

In [121]:
A = 10*np.random.rand(5)
A

array([1.54828817, 5.34995177, 5.4338715 , 9.84266967, 2.51787387])

In [122]:
#rounding floatiing points
np.floor(A)

array([1., 5., 5., 9., 2.])

In [123]:
#implemented by 1 
np.ceil(A)

array([ 2.,  6.,  6., 10.,  3.])