In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])

In [4]:
b = np.array((1, 2, 3, 4, 5))

In [4]:
print(a)

[1 2 3 4 5]


In [5]:
type(a)

numpy.ndarray

In [28]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
a.ndim

2

In [29]:
a.shape

(2, 3)

In [12]:
b = np.array([[1, 2, 3], [4, 5, 9]])

In [14]:
b[1, 2]

9

In [25]:
c = np.array([[[1, 2, 3], [4, 5, 6], [0, 0, -1]], [[-1, -2, -3], [-4, -5, -6], [0, 0, 1]]])


In [26]:
c.ndim

3

In [22]:
c[1, 0, 2]

-3

In [24]:
type(c)

numpy.ndarray

In [26]:
c.shape

(2, 3, 3)

In [27]:
c.shape[0]

2

In [28]:
c.shape[1]

3

In [29]:
c.shape[2]

3

In [30]:
a = np.array([2])

In [31]:
a.ndim

1

In [32]:
b = np.array(3)

In [33]:
b.ndim

0

In [34]:
c.size

18

In [35]:
c.nbytes

144

In [37]:
a = np.arange(100)

In [38]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [40]:
a = np.arange(20, 100)
print(a)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [42]:
a = np.arange(20, 100, 3) # for i in range(20, 100, 3)
print(a)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [43]:
print(list(range(20)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [44]:
print(range(0, 20))

range(0, 20)


In [3]:
a = np.random.permutation(np.arange(10))
a

array([3, 2, 5, 8, 4, 7, 1, 0, 9, 6])

In [56]:
np.random.randint?

In [62]:
np.random.randint(20, 30)

28

In [30]:
a = np.round(10 * np.random.rand(2, 3))
a

array([[8., 5., 9.],
       [8., 1., 5.]])

In [21]:
a + (np.arange(2).reshape(2, 1))

array([[ 3., 10.,  3.],
       [ 8.,  3.,  4.]])

In [23]:
a + 3

array([[ 6., 13.,  6.],
       [10.,  5.,  6.]])

In [28]:
b = np.arange(2)
b

array([0, 1])

In [29]:
c = np.round(10 * np.random.rand(2, 2))
c

array([[5., 9.],
       [4., 9.]])

In [34]:
d = np.hstack((a, c))
d

array([[ 3., 10.,  3.,  5.,  9.],
       [ 7.,  2.,  3.,  4.,  9.]])

In [71]:
n = np.random.permutation(a)
n

array([[8., 5., 9.],
       [8., 1., 5.]])

In [73]:
m = np.random.permutation(np.arange(9))
m

array([0, 3, 2, 7, 6, 4, 8, 5, 1])

In [76]:
m.sort()
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.sort(m)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
mm = m[: : -1]
mm

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [79]:
r = np.array(["hello", 'how are', '12ui', '89dd', 'joi7'])
r.sort()
r

array(['12ui', '89dd', 'hello', 'how are', 'joi7'], dtype='<U7')

In [8]:
b = np.random.rand(1000000)
b

array([0.82147108, 0.84462289, 0.00277465, ..., 0.00094701, 0.76426186,
       0.6335163 ])

In [19]:
%timeit sum(b)
%timeit np.sum(b)

40.7 ms ± 86.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
225 µs ± 2.95 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [23]:
def mysum(G):
    s = 0
    for x in G:
        s += x
    return s

In [24]:
%timeit mysum(b)

49.4 ms ± 1.36 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
