In [1]:
import numpy as np

In [8]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#starting from 0 to 10 and making 10 elements.
B = np.random.randint(0,10,(1,10))
B

array([[3, 7, 3, 3, 1, 7, 5, 0, 7, 6]])

In [4]:
B.shape

(1, 10)

In [5]:
A.shape

(10,)

In [6]:
C = A[np.newaxis, :]
C.shape

(1, 10)

In [12]:
B.shape

(1, 10)

In [14]:
D = B + C 
D

array([[ 3,  8,  5,  6,  5, 12, 11,  7, 15, 15]])

In [15]:
D.shape

(1, 10)

In [17]:
D = np.squeeze(D)

In [18]:
D.shape

(10,)

In [19]:
D

array([ 3,  8,  5,  6,  5, 12, 11,  7, 15, 15])