In [5]:
# create an array myArray1 using numpy.random.rand for 50 values multiplying by 10
import numpy as np
myArray1 = 10*np.random.rand(50)

In [6]:
# remove Decimal point values of myArray1
myArray1 = np.floor(myArray1)

In [8]:
# make another array myArray2 and store only numbers that are greater than 5 from myArray1
myArray2 = myArray1[myArray1>5]
myArray2

array([6., 9., 7., 6., 6., 6., 9., 7., 6., 6., 7., 9., 7., 7., 8., 9., 7.,
       7.])

In [11]:
# sort myArray2 in ascending order, sort myArray1 in descending order
myArray2.sort()
myArray2
myArray1.sort()
myArray1

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 3.,
       3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5., 6., 6.,
       6., 6., 6., 6., 7., 7., 7., 7., 7., 7., 7., 8., 9., 9., 9., 9.])

In [12]:
myArray1 = myArray1[::-1]
myArray1

array([9., 9., 9., 9., 8., 7., 7., 7., 7., 7., 7., 7., 6., 6., 6., 6., 6.,
       6., 5., 5., 5., 5., 5., 4., 4., 4., 4., 4., 4., 3., 3., 3., 3., 3.,
       2., 2., 2., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.])